# -*- coding: utf-8 -*-
"""Copy of trainingchatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s564tL42RqbXtThbpRDnKFsHapQ63Kmb
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers datasets

import json
from datasets import Dataset
dataset_path = '/content/drive/MyDrive/Senior/Chatbot/final_clean_training_dataset1.json'
with open(dataset_path, 'r') as f:
    data = json.load(f)
dataset = Dataset.from_list(data)

from transformers import AutoModelForCausalLM, AutoTokenizer
model_name = "microsoft/DialoGPT-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.add_special_tokens({'additional_special_tokens': ['<|sep|>']})
model = AutoModelForCausalLM.from_pretrained(model_name)
model.resize_token_embeddings(len(tokenizer))

def preprocess_function(examples):
    dialogues = [f"{user} <|sep|> {bot} <|endoftext|>" for user, bot in zip(examples["User"], examples["Bot"])]
    model_inputs = tokenizer(dialogues, max_length=128, truncation=True, padding="max_length")
    model_inputs["labels"] = model_inputs["input_ids"].copy()
    return model_inputs

tokenizer.pad_token = tokenizer.eos_token

tokenized_dataset = dataset.map(preprocess_function, batched=True)

split_dataset = tokenized_dataset.train_test_split(test_size=0.1)
train_dataset = split_dataset["train"]
val_dataset = split_dataset["test"]

from transformers import Trainer, TrainingArguments
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=30,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    learning_rate=5e-5,
    warmup_steps=50,
    weight_decay=0.005,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    logging_steps=20,
    max_grad_norm=1.0,
    fp16=True,
    save_total_limit=2,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)
trainer.train()

model.save_pretrained("/content/drive/MyDrive/Senior/Chatbot/modelv4")
tokenizer.save_pretrained("/content/drive/MyDrive/Senior/Chatbot/modelv4")

from transformers import pipeline

chatbot = pipeline("text-generation", model="/content/drive/MyDrive/Senior/Chatbot/modelv4", tokenizer=tokenizer)
response = chatbot("how do I treat apple scab leaf?", max_length=50)
print(response[0]["generated_text"])

"""# Testing"""

from transformers import pipeline, AutoTokenizer
import re

# Load your fine-tuned model and tokenizer
model_path = "/content/drive/MyDrive/Senior/Chatbot/modelv4"  # Your model path
tokenizer = AutoTokenizer.from_pretrained(model_path)

# Create the pipeline with specific parameters
chatbot = pipeline(
    "text-generation",
    model=model_path,
    tokenizer=tokenizer,
    do_sample=True,
    top_p=0.92,
    temperature=0.7,
    no_repeat_ngram_size=3
)

def chat_with_model():
    print("Plant Disease Assistant: Hello! I can help with plant disease questions. Type 'exit' to end the conversation.")

    # Keep track of the conversation state
    current_disease = None
    conversation_history = {}  # Map of disease -> {questions:{}, responses:{}}
    previous_question = None
    previous_response = None

    while True:
        # Get user input
        user_input = input("You: ")

        if user_input.lower() == 'exit':
            print("Plant Disease Assistant: Goodbye!")
            break

        # Check if this is a follow-up question (e.g., "how do I treat it?")
        is_followup = False
        if re.search(r'\b(it|this|that|the disease|the problem)\b', user_input.lower()):
            is_followup = True

        # Identify potential disease in the question
        disease_keywords = [
            "early blight", "late blight", "apple scab", "black rot", "cedar apple rust",
            "powdery mildew", "downy mildew", "leaf spot", "bacterial spot", "tomato mosaic virus",
            "fusarium wilt", "verticillium wilt", "septoria leaf spot", "anthracnose"
        ]

        # Try to extract disease name from user input
        detected_disease = None
        for disease in disease_keywords:
            if disease in user_input.lower():
                detected_disease = disease
                current_disease = disease
                break

        # Create an enhanced prompt based on conversation state
        if is_followup and current_disease:
            # If it's a follow-up, include disease context
            prompt = f"For {current_disease}: {user_input}"

            # If it's "how do I treat it" after identifying symptoms, create a more specific prompt
            if "treat" in user_input.lower() and previous_question and "identify" in previous_question.lower():
                prompt = f"Treatment for {current_disease}: {user_input}"
        else:
            # Regular prompt with some structure
            prompt = f"Question about plant disease: {user_input}"
            if detected_disease:
                prompt = f"Question about {detected_disease}: {user_input}"

        # Generate response - try up to 3 times if we get short or repetitive answers
        max_attempts = 3
        best_answer = None
        best_answer_length = 0

        for attempt in range(max_attempts):
            # Adjust temperature slightly on each attempt
            temp = 0.7 + (attempt * 0.1)

            # Generate response using pipeline
            response = chatbot(
                prompt,
                max_length=len(prompt.split()) + 50,
                truncation=True,
                temperature=temp
            )

            # Extract only the new generated text
            generated_text = response[0]["generated_text"]
            answer = generated_text[len(prompt):].strip()

            # Check if this answer is better than previous attempts
            if len(answer.split()) > best_answer_length and answer != previous_response:
                best_answer = answer
                best_answer_length = len(answer.split())

            # If we got a good answer, no need to try more
            if best_answer_length >= 8:
                break

        # Use best answer or fallback
        if best_answer_length < 5:
            answer = "I need more information about this plant disease. Could you rephrase your question?"
        else:
            answer = best_answer

        # Print the response
        print(f"Plant Disease Assistant: {answer}")

        # Update conversation tracking
        previous_question = user_input
        previous_response = answer

        # Store in history for potential future reference
        if current_disease:
            if current_disease not in conversation_history:
                conversation_history[current_disease] = {"questions": [], "responses": []}
            conversation_history[current_disease]["questions"].append(user_input)
            conversation_history[current_disease]["responses"].append(answer)

chat_with_model()

